const data = [

    {
        "_id": "5ff4fb7cd89993a89cc65456",
        "pokemon": "pidgeot",
        "id": 23,
        "species_id": 18,
        "height": 15,
        "weight": 395,
        "base_experience": 216,
        "type_1": "normal",
        "type_2": "flying",
        "attack": 80,
        "defense": 75,
        "hp": 83,
        "special_attack": 70,
        "special_defense": 70,
        "speed": 101,
        "ability_1": "keen-eye",
        "ability_2": "tangled-feet",
        "ability_hidden": "big-pecks",
        "color_1": "#A8A878",
        "color_2": "#A890F0",
        "color_f": "#A8A295",
        "egg_group_1": "flying",
        "egg_group_2": "NA",
        "url_image": "http://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png",
        "generation_id": 1,
        "evolves_from_species_id": "17",
        "evolution_chain_id": 6,
        "shape_id": 9,
        "shape": "wings",
        "pokebase": "pidgeot",
        "pokedex": "http://www.pokemon.com/us/pokedex/pidgeot"
    },
    {
        "_id": "5ff4fb7cd89993a89cc6544e",
        "pokemon": "metapod",
        "id": 15,
        "species_id": 11,
        "height": 7,
        "weight": 99,
        "base_experience": 72,
        "type_1": "bug",
        "type_2": "NA",
        "attack": 20,
        "defense": 55,
        "hp": 50,
        "special_attack": 25,
        "special_defense": 25,
        "speed": 30,
        "ability_1": "shed-skin",
        "ability_2": "NA",
        "ability_hidden": "NA",
        "color_1": "#A8B820",
        "color_2": "NA",
        "color_f": "NA",
        "egg_group_1": "bug",
        "egg_group_2": "NA",
        "url_image": "http://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png",
        "generation_id": 1,
        "evolves_from_species_id": "10",
        "evolution_chain_id": 4,
        "shape_id": 2,
        "shape": "squiggle",
        "pokebase": "metapod",
        "pokedex": "http://www.pokemon.com/us/pokedex/metapod"
    },
    {
        "_id": "5ff4fb7cd89993a89cc65448",
        "pokemon": "charizard-mega-y",
        "id": 9,
        "species_id": 6,
        "height": 17,
        "weight": 1005,
        "base_experience": 285,
        "type_1": "fire",
        "type_2": "flying",
        "attack": 104,
        "defense": 78,
        "hp": 78,
        "special_attack": 159,
        "special_defense": 115,
        "speed": 100,
        "ability_1": "drought",
        "ability_2": "NA",
        "ability_hidden": "NA",
        "color_1": "#F08030",
        "color_2": "#A890F0",
        "color_f": "#DE835E",
        "egg_group_1": "monster",
        "egg_group_2": "dragon",
        "url_image": "http://assets.pokemon.com/assets/cms2/img/pokedex/full/006_f3.png",
        "generation_id": "NA",
        "evolves_from_species_id": "NA",
        "evolution_chain_id": "NA",
        "shape_id": "NA",
        "shape": "NA",
        "pokebase": "charizard",
        "pokedex": "http://www.pokemon.com/us/pokedex/charizard"
    }
];

export default data;
